# Generated by Django 4.2.1 on 2023-05-16 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turufapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cnum', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('Nmae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turufapp.turufs')),
            ],
        ),
    ]
