# Generated by Django 4.2.1 on 2023-05-16 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turufapp', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Nmae',
            new_name='Name',
        ),
    ]
